namespace SIDStream
{
    // Class used to serialize and deserialize a specific skin's parameters from JSON
    internal class Skin
    {
        public string bgImage { get; set; }
        public string mediaLabel { get; set; }
        public string mediaLabelBGColor { get; set; }
        public string mediaLabelFGColor { get; set; }
        public int mediaLabelX { get; set; }
        public int mediaLabelY { get; set; }
        public string infoLabel { get; set; }
        public string infoLabelBGColor { get; set; }
        public string infoLabelFGColor { get; set; }
        public int infoLabelX { get; set; }
        public int infoLabelY { get; set; }
        public string copyrightLabel { get; set; }
        public string copyrightLabelBGColor { get; set; }
        public string copyrightLabelFGColor { get; set; }
        public int copyrightLabelX { get; set; }
        public int copyrightLabelY { get; set; }
        public int volumeSliderX { get; set; }
        public int volumeSliderY { get; set; }
        public string volumeSliderBGColor { get; set; }
        public string volumeSliderFGColor { get; set; }
        public int currentTrackLabelX { get; set; }
        public int currentTrackLabelY { get; set; }
        public string currentTrackLabelBGColor { get; set; }
        public string currentTrackLabelFGColor { get; set; }
        public string logoImage { get; set; }
        public int logoX { get; set; }
        public int logoY { get; set; }
        public int logoWidth { get; set; }
        public int logoHeight { get; set; }
        public string settingsButtonImage { get; set; }
        public string settingsButtonHoverImage { get; set; }
        public string settingsButtonPressedImage { get; set; }
        public int settingsButtonX { get; set; }
        public int settingsButtonY { get; set; }
        public int settingsButtonWidth { get; set; }
        public int settingsButtonHeight { get; set; }
        public string playButtonImage { get; set; }
        public string playButtonHoverImage { get; set; }
        public string playButtonPressedImage { get; set; }
        public int playButtonX { get; set; }
        public int playButtonY { get; set; }
        public int playButtonWidth { get; set; }
        public int playButtonHeight { get; set; }
        public string stopButtonImage { get; set; }
        public string stopButtonHoverImage { get; set; }
        public string stopButtonPressedImage { get; set; }
        public int stopButtonX { get; set; }
        public int stopButtonY { get; set; }
        public int stopButtonWidth { get; set; }
        public int stopButtonHeight { get; set; }
        public string openButtonImage { get; set; }
        public string openButtonHoverImage { get; set; }
        public string openButtonPressedImage { get; set; }
        public int openButtonX { get; set; }
        public int openButtonY { get; set; }
        public int openButtonWidth { get; set; }
        public int openButtonHeight { get; set; }
        public string closeButtonImage { get; set; }
        public string closeButtonHoverImage { get; set; }
        public string closeButtonPressedImage { get; set; }
        public int closeButtonX { get; set; }
        public int closeButtonY { get; set; }
        public int closeButtonWidth { get; set; }
        public int closeButtonHeight { get; set; }
        public string previousButtonImage { get; set; }
        public string previousButtonHoverImage { get; set; }
        public string previousButtonPressedImage { get; set; }
        public int previousButtonX { get; set; }
        public int previousButtonY { get; set; }
        public int previousButtonWidth { get; set; }
        public int previousButtonHeight { get; set; }
        public string nextButtonImage { get; set; }
        public string nextButtonHoverImage { get; set; }
        public string nextButtonPressedImage { get; set; }
        public int nextButtonX { get; set; }
        public int nextButtonY { get; set; }
        public int nextButtonWidth { get; set; }
        public int nextButtonHeight { get; set; }
        public string bgSettingsImage { get; set; }
        public string okButtonImage { get; set; }
        public string okButtonHoverImage { get; set; }
        public string okButtonPressedImage { get; set; }
        public int okButtonX { get; set; }
        public int okButtonY { get; set; }
        public int okButtonWidth { get; set; }
        public int okButtonHeight { get; set; }
        public string cancelButtonImage { get; set; }
        public string cancelButtonHoverImage { get; set; }
        public string cancelButtonPressedImage { get; set; }
        public int cancelButtonX { get; set; }
        public int cancelButtonY { get; set; }
        public int cancelButtonWidth { get; set; }
        public int cancelButtonHeight { get; set; }
        public string selectSkinLabel { get; set; }
        public string selectSkinLabelBGColor { get; set; }
        public string selectSkinLabelFGColor { get; set; }
        public int selectSkinLabelX { get; set; }
        public int selectSkinLabelY { get; set; }
        public int skinComboBoxX { get; set; }
        public int skinComboBoxY { get; set; }
        public int skinComboBoxHeight { get; set; }
        public int skinComboBoxWidth { get; set; }
        public string skinComboBoxBGColor { get; set; }
        public string skinComboBoxFGColor { get; set; }
    }
}


